### ISSUE TITLE
Make a WebSocket in JavaScript in chart.html to handle live data

### ISSUE THREAD

**Issue by bilusss** [bilusss/TradingSignalApp#10]

**Comment by bilusss** [comment]
There are like 20-30 lines of code needed to handle LiveData from WebSocket
?Consider stopping WebSocket when user changes timeline, changes into other chart?
By default, there is a certain amount of time after which the WebSocket stops.

**Comment by bilusss** [comment]
Unable user to spam with WebSocket requests as our API might be banned (only in real scenario)
As long as we use Binance Testnet there should be no problem with this (70% sure 😺) unless we get IP banned.

**Comment by AntoniPokrzywa** [comment]
Web socket is overkill for such an app my brother

**Comment by AntoniPokrzywa** [comment]
If you are really into web sockets learn about them first than consider implementing it, if you really want live data feel free to do it

**Comment by bilusss** [comment]
Too late my brother, I've already done it.
Hope you will enjoy this one
ISSUE CLOSED! 😄

**Comment by bilusss** [comment]
Too late my brother, I've already done it.
Hope you will enjoy this one
ISSUE CLOSED! 😄
